### ISSUE TITLE
Bot mostly only replies non english spam messages

### ISSUE THREAD

**Issue by drishal** [DavideGalilei/markinim#5]
There is a small problem with the bot: once some telegram bots attacked my group, but the problem is  markinim most of the times  sends only those spam messages/gibberish
for example 
![image](https://user-images.githubusercontent.com/32875739/181778289-9d487958-a894-4875-86ae-b984ab589dda.png)

Is there any way for the bot to be in english only mode so it does not reply with those old spam messages?

**Comment by DavideGalilei** [comment]
There is no way to force english only messages, however there are 2 workarounds:
 - By using the /deletefrom command, which deletes from the database all messages a spammer sent. You can use this command both in reply to someone, or by manually inserting the user id, example: `/deletefrom 123`. Note: this action cannot be undone, and it **doesn't** ask for confirmation
 - By deleting all messages from the database, using the /delete command (it asks for a confirmation)

**Comment by drishal** [comment]
> There is no way to force english only messages, however there are 2 workarounds:
> 
>     * By using the /deletefrom command, which deletes from the database all messages a spammer sent. You can use this command both in reply to someone, or by manually inserting the user id, example: `/deletefrom 123`. Note: this action cannot be undone, and it **doesn't** ask for confirmation
> 
>     * By deleting all messages from the database, using the /delete command (it asks for a confirmation)

But the problem is, it was atleast 40 bots which attacked the group during that time...and also it reads old deleted messages, atleast is there a way to prevent the bot from reading from deleted messages then?

**Comment by DavideGalilei** [comment]
> it reads old deleted messages

It doesn't actually read old messages, it just stores every message upon receiving it. It is not possible to know whether a message has been deleted, due to Telegram BotAPI limitations (the bot doesn't receive updates when a message gets deleted)

Unfortunately, unless you want to delete all the messages from the bot memory, you must use the /deletefrom one by one. I don't think I can do much about it, since that means that I would have to detect spam or repeated messages, and that's resource expensive :(

**Comment by drishal** [comment]
Maybe you can instead allow an option for proper english only?

**Comment by DavideGalilei** [comment]
That would require natural language processing, and I don't plan to add that since it would be restricted to english only. One may argue that the SFW filter is english only as well, but the reason for it is that it's not as resource expensive as NLP, and that it's easy to implement

**Comment by drishal** [comment]
Anyways ran the delete command on the bot, and now atleast it does not spam the old spam messages...closing the issue for now tho please look into reducing the issue
